/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ---- RAMPS -------------------------------------------------------
        // Added because colour kept escaping the token system at the call
        // site: 173 uses of opacity-derived values across 28 distinct
        // variants, none of them contrast-checked. That is how sandink/70
        // shipped at 3.41:1 in the bottom nav -- you cannot measure a colour
        // that does not exist until render.
        //
        // Every step below is measured against #FFFFFF (card) and #FBF7F1
        // (page). Generated by one ladder from three anchors, so the ramps
        // stay related to each other; re-deriving is a script, not a redraw.
        //
        // These do NOT replace the semantic tokens below. Components keep
        // using sea/mist/line; the ramps are the palette those are drawn from
        // and the source for the tints that used to be alpha guesses.
        teal: {
          50: '#F4F6F3',
          100: '#E3ECE9',
          200: '#C1D7D4',
          300: '#93BBB8',
          400: '#5E9B98',
          500: '#2A7C79',
          600: '#00625F',
          700: '#045451',
          800: '#0A4341',
          900: '#10322F',
        },
        coral: {
          50: '#FCF6F1',
          100: '#F9EBE5',
          200: '#F1D4CB',
          300: '#E6B6A8',
          400: '#DA9481',
          500: '#CE725A',
          600: '#C4573A',
          700: '#A54B33',
          800: '#803D2A',
          900: '#5A2D21',
        },
        slate: {
          50: '#F8F6F3',
          100: '#EFECE9',
          200: '#DBD8D3',
          300: '#C1BCB7',
          400: '#A49D96',
          500: '#867E76',
          600: '#6E655C',
          700: '#5F564F',
          800: '#4C453F',
          900: '#39332E',
        },

        // Danger is deliberately NOT from the coral ramp. Coral is warm-red,
        // so a coral-derived error would share a hue family with the brand
        // accent and read as on-brand rather than alarming. Wael's call.
        // #B91C1C is 6.47:1 on card and 6.06:1 on page, and sits furthest
        // from coral of the candidates (RGB distance 67 vs 58 for red-600).
        //
        // It also replaces text-red-600, which is what the code uses today at
        // 4.52:1 on the page background -- passing by 0.02.
        danger: '#B91C1C',
        dangertint: '#FDECEC',
        success: '#2A7C79',      // teal-500, 4.62:1 on page
        successtint: '#E3ECE9',  // teal-100
        warning: '#867E76',      // slate-500, 3.74:1 -- large text / UI only

        // Salka — teal, silver & gold (warm neutrals, cool teal accent — updated Aug 2026)
        // Rationale: the palette read as cold since every neutral had a cool teal-grey
        // undertone. Kept the teal brand color exactly as-is; warmed every neutral around
        // it instead, so teal now stands out as the one cool-toned element rather than
        // blending into a cool-grey family.
        night: '#FBF7F1',     // page background — warm ivory (was #F4F7F7, cool silver)
        shell: '#FFFFFF',     // card background
        shellup: '#F4EEE3',   // elevated surface (header, active tab, thumbnails) — warm tint (was #EAF1F0)
        line: '#E8E1D6',      // borders — warm light grey (was #E1E8E7, cool silver)
        sea: '#00625F',       // brand primary = teal-600. Was #0A5F5E, whose comment claimed it
                              // matched the logo exactly; Wael confirmed the logo is #00625F.
                              // 14/765 in RGB, invisible, and both pass AA -- but only one is right.
        seadeep: '#063A39',   // primary hover/pressed — unchanged
        sand: '#B8934A',      // secondary/accent — DECORATIVE ONLY: star icons, tinted backgrounds.
                              // 2.69:1 on night and 2.87:1 on shell, so it must never carry text.
        sandink: '#6E572B',   // the same hue and saturation, darker — this is the one for gold TEXT.
                              // 6.43:1 on night, 6.86:1 on shell, 5.94:1 on shellup. All pass AA.
        linestrong: '#A3875C',// form-control borders only. `line` is 1.30:1 against a card, which is
                              // fine for decorative card edges but fails WCAG 1.4.11's 3:1 for the
                              // boundary of an input. This is 3.40:1 on shell, 3.19:1 on night.
        foam: '#231F1A',      // primary text — warm near-black (was #17302E, cool teal-black)
        mist: '#6E655C'       // secondary/muted text — warm grey (was #64716F, cool silver-gray)
      },
      fontFamily: { arabic: ['"IBM Plex Sans Arabic"', 'system-ui', 'sans-serif'] }
    }
  },
  plugins: []
}
