/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ---- RAMPS -------------------------------------------------------
        // Added because colour kept escaping the token system at the call
        // site: 173 uses of opacity-derived values across 28 distinct
        // variants, none of them contrast-checked. That is how sandink/70
        // shipped at 3.41:1 in the bottom nav -- you cannot measure a colour
        // that does not exist until render.
        //
        // Every step below is measured against #FFFFFF (card) and #FBF7F1
        // (page). Generated by one ladder from three anchors, so the ramps
        // stay related to each other; re-deriving is a script, not a redraw.
        //
        // These do NOT replace the semantic tokens below. Components keep
        // using sea/mist/line; the ramps are the palette those are drawn from
        // and the source for the tints that used to be alpha guesses.
        teal: {
          50: '#F4F6F3',
          100: '#E3ECE9',
          200: '#C1D7D4',
          300: '#93BBB8',
          400: '#5E9B98',
          500: '#2A7C79',
          600: '#00625F',
          700: '#045451',
          800: '#0A4341',
          900: '#10322F',
        },
        coral: {
          50: '#FCF6F1',
          100: '#F9EBE5',
          200: '#F1D4CB',
          300: '#E6B6A8',
          400: '#DA9481',
          500: '#CE725A',
          600: '#C4573A',
          700: '#A54B33',
          800: '#803D2A',
          900: '#5A2D21',
        },
        slate: {
          50: '#F8F6F3',
          100: '#EFECE9',
          200: '#DBD8D3',
          300: '#C1BCB7',
          400: '#A49D96',
          500: '#867E76',
          600: '#6E655C',
          700: '#5F564F',
          800: '#4C453F',
          900: '#39332E',
        },

        // ---- STATE COLOURS -----------------------------------------------
        // Each state is a TRIPLET -- text, background, line -- not a single hex.
        // A single token can only ever colour text; a warning that needs to read
        // as a box needs all three, and inventing the other two at the call site
        // is how the opacity variants got started.
        //
        // WARNING IS AMBER, NOT GREY. It shipped as slate-500 in the first pass,
        // which passes contrast and says nothing: it is the same colour as
        // secondary text. That gap is why the admin board reads as "too much
        // red" -- with no warning colour, red was doing two jobs, "this failed"
        // and "look at this". A late order and a refund failure are not the
        // same news and should not be the same colour.
        //
        // Danger is deliberately NOT from the coral ramp: coral is warm-red, so
        // a coral-derived error would share a hue family with the brand accent
        // and read as on-brand rather than alarming. It also replaces
        // text-red-600, which the code used at 4.52:1 on the page -- passing by
        // 0.02.
        //
        // Text values are measured on card #FFFFFF, page #FBF7F1, elevated
        // #F4EEE3 AND on their own tint, which is the ground they most often
        // sit on. success is teal-600 rather than teal-500 for exactly that
        // reason: 500 was 4.44:1 on its own tint, under the 4.5 line.
        danger: '#B91C1C',       // 6.47 / 6.06 / 5.66 / 5.66 on its tint
        dangerbg: '#FAEDEA',
        dangerline: '#EDC2C0',
        warning: '#8A5B00',      // 5.87 / 5.50 / 5.08 / 5.26 on its tint
        warningbg: '#F7F2E8',
        warningline: '#E1D3B9',
        success: '#00625F',      // 7.21 / 6.76 / 6.24 / 6.49 on its tint
        successbg: '#F0F4F1',
        successline: '#C8DBD8',

        // Salka — teal, silver & gold (warm neutrals, cool teal accent — updated Aug 2026)
        // Rationale: the palette read as cold since every neutral had a cool teal-grey
        // undertone. Kept the teal brand color exactly as-is; warmed every neutral around
        // it instead, so teal now stands out as the one cool-toned element rather than
        // blending into a cool-grey family.
        // 2026-08-19, Wael: the ground goes white. THREE jobs only -- page
        // background, image-container background, image-container border. The
        // rest of the palette stays warm; an earlier pass spread the neutral
        // across cards, shelves and headers, which is not what was asked.
        night: '#FFFFFF',     // page background — white (was #FBF7F1, warm ivory)
        shell: '#FFFFFF',     // card background
        shellup: '#F4EEE3',   // elevated surface (header, active tab, tints) — warm
        line: '#E8E1D6',      // borders — warm light grey
        // The image container, and ONLY the image container: a surface that
        // sits behind a photograph, where a warm tint casts onto the food.
        imgbg: '#F5F5F5',
        imgline: '#E5E5E5',
        sea: '#00625F',       // brand primary = teal-600. Was #0A5F5E, whose comment claimed it
                              // matched the logo exactly; Wael confirmed the logo is #00625F.
                              // 14/765 in RGB, invisible, and both pass AA -- but only one is right.
        seadeep: '#063A39',   // primary hover/pressed — unchanged
        // sand / sandink / linestrong were removed once the last call site moved to
        // coral. Not for bytes -- Tailwind only emits CSS for classes that appear in
        // source, so an unused token already costs nothing. They are gone so nobody
        // reaches for them again: sand measured 2.87 / 2.69 / 2.49 against the three
        // grounds and fails WCAG 1.4.11's 3:1 on all of them, which is exactly the
        // failure this migration existed to fix.
        foam: '#231F1A',      // primary text — warm near-black (was #17302E, cool teal-black)
        mist: '#6E655C'       // secondary/muted text — warm grey (was #64716F, cool silver-gray)
      },
      fontFamily: { arabic: ['"IBM Plex Sans Arabic"', 'system-ui', 'sans-serif'] }
    }
  },
  plugins: []
}
