#!/usr/bin/env node
// Regenerate src/components/Icon.tsx from @phosphor-icons/core.
//
//   npm i -D @phosphor-icons/core     # if it is not installed
//   npm run build:icons
//
// WHY GENERATE RATHER THAN IMPORT. @phosphor-icons/react would be the obvious
// choice, but it ships a React component per icon and this app already sits over
// Vite's bundle-size warning -- the page-weight work took the entry from 5,161 kB
// to 821 kB and it is not worth giving any of that back for 22 shapes. Inlining
// the path data keeps the runtime dependency at zero and the CDN request count
// at zero, which is what the previous Font Awesome file did too.
//
// TO ADD AN ICON: put it in MAP below with its Phosphor name, run this, commit
// the regenerated Icon.tsx. The script fails loudly if a name does not exist in
// both weights rather than silently emitting a broken glyph.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const A = 'node_modules/@phosphor-icons/core/assets'
const OUT = 'src/components/Icon.tsx'

// our name -> phosphor name. Two are deliberate reinterpretations, not renames:
//   boxOpen       -> package      a parcel, which is what a pickup errand is
//   rectangleList -> list-dashes  a list of items, not a bulleted paragraph
const MAP = [
  ['forkKnife', 'fork-knife'], ['boxOpen', 'package'], ['bagShopping', 'shopping-bag'],
  ['receipt', 'receipt'], ['magnifyingGlass', 'magnifying-glass'], ['locationDot', 'map-pin'],
  ['star', 'star'], ['clock', 'clock'], ['minus', 'minus'], ['plus', 'plus'],
  ['clone', 'copy'], ['moneyBill', 'money'], ['mobileScreen', 'device-mobile'],
  ['house', 'house'], ['rectangleList', 'list-dashes'], ['penToSquare', 'note-pencil'],
  ['creditCard', 'credit-card'], ['cartShopping', 'shopping-cart'], ['chevronLeft', 'caret-left'],
  ['truck', 'truck'], ['tag', 'tag'], ['circleUser', 'user-circle'],
  ['check', 'check'], ['x', 'x'], ['warning', 'warning'],
  ['pill', 'pill'], ['moped', 'moped-front'], ['repeat', 'repeat'],
  ['envelope', 'envelope'], ['chatCircle', 'chat-circle'], ['broadcast', 'broadcast'],
  ['paperclip', 'paperclip'], ['arrowUp', 'arrow-up'], ['image', 'image'],
  ['briefcase', 'briefcase'], ['wallet', 'wallet'], ['clipboardText', 'clipboard-text'],
  ['bell', 'bell'], ['phone', 'phone'], ['thumbsDown', 'thumbs-down'],
  ['question', 'question'], ['camera', 'camera'], ['coins', 'coins'],
  ['arrowCounterClockwise', 'arrow-counter-clockwise'], ['pencilSimple', 'pencil-simple'],
  ['arrowRight', 'arrow-right'], ['user', 'user'],
  ['hourglass', 'hourglass'], ['flask', 'flask'], ['van', 'van'], ['moon', 'moon'],
  ['gear', 'gear'], ['arrowUturn', 'arrow-u-up-left'], ['megaphone', 'megaphone'],
  ['storefront', 'storefront'], ['speakerSlash', 'speaker-slash'], ['link', 'link'],
  ['chartLineDown', 'chart-line-down'], ['arrowDown', 'arrow-down'], ['trash', 'trash'],
  ['folders', 'folders'], ['bellRinging', 'bell-ringing'], ['siren', 'siren'],
  ['mobileSlash', 'device-mobile-slash'], ['handPointing', 'hand-pointing'], ['car', 'car'],
  ['trafficSignal', 'traffic-signal'], ['users', 'users'], ['chartBar', 'chart-bar'],
  ['thumbsUp', 'thumbs-up'], ['prohibit', 'prohibit'], ['note', 'note'],
  ['stethoscope', 'stethoscope'], ['handSoap', 'hand-soap'], ['basket', 'basket'],
  ['sprayBottle', 'spray-bottle'], ['umbrella', 'umbrella-simple'],
  ['baby', 'baby'], ['carrot', 'carrot'], ['cheese', 'cheese'],
]

// Icons that also ship a FILLED variant. Deliberately a short list, not all 80:
// the fill weight is a second full copy of every path, so generating it for the
// whole set would add ~12kB gzip to carry five nav icons. Add a name here only
// when something actually renders a filled state.
const FILLED = ['house', 'truck', 'tag', 'cartShopping', 'circleUser']

if (!existsSync(A)) {
  console.error(`${A} not found. Run:  npm i -D @phosphor-icons/core`)
  process.exit(2)
}

/** Phosphor emits one <path> per icon. More than one means the shape would be
 *  clipped if we only took the first, so refuse rather than emit it. */
function pathOf(file, label) {
  if (!existsSync(file)) { console.error(`missing: ${label} (${file})`); process.exit(1) }
  const found = [...readFileSync(file, 'utf8').matchAll(/<path\s+d="([^"]+)"/g)].map(m => m[1])
  if (found.length !== 1) {
    console.error(`${label} has ${found.length} paths; this generator assumes exactly 1`)
    process.exit(1)
  }
  return found[0]
}

const names = MAP.map(([n]) => n)
const lines = []
lines.push(`// GENERATED by scripts/build-icons.mjs from @phosphor-icons/core. Do not edit by
// hand -- add to MAP in that script and re-run instead.
//
// Path data is inlined so there is no runtime dependency and no CDN request.
// Phosphor draws every icon on a 256x256 grid, so they are all optically the
// same size at the same className; the previous Font Awesome set used a
// per-icon viewBox and was not.
//
// Both weights are complete for all 1,512 Phosphor icons, so \`variant\` is a real
// choice. Under Font Awesome Free it was not: only a handful of shapes had an
// outline, so variant="regular" silently fell back to solid and active states
// had to lean on colour alone -- which is what fails for a colour-blind operator.`)
lines.push('')
lines.push('export type IconName =')
for (let i = 0; i < names.length; i += 4) {
  lines.push((i ? '  | ' : '  ') + names.slice(i, i + 4).map(n => `'${n}'`).join(' | '))
}
lines.push('')
for (const [weight, konst, suffix] of [['bold', 'BOLD', '-bold']]) {
  lines.push('')
  lines.push(`const ${konst}: Record<IconName, string> = {`)
  for (const [our, ph] of MAP) {
    lines.push(`  ${our}: '${pathOf(`${A}/${weight}/${ph}${suffix}.svg`, `${our} (${weight})`)}',`)
  }
  lines.push('}')
}
lines.push('')
lines.push('export type FilledIconName =')
lines.push('  ' + FILLED.map(n => `'${n}'`).join(' | '))
lines.push('')
lines.push('const FILL: Record<FilledIconName, string> = {')
for (const our of FILLED) {
  const ph = MAP.find(([o]) => o === our)?.[1]
  if (!ph) { console.error(`FILLED lists ${our}, which is not in MAP`); process.exit(2) }
  lines.push(`  ${our}: '${pathOf(`${A}/fill/${ph}-fill.svg`, `${our} (fill)`)}',`)
}
lines.push('}')

lines.push(`
// Bold weight, not regular: at the sizes these render at, regular's hairlines
// go muddy next to IBM Plex Sans Arabic's stems. Bold matches the text colour
// weight so an icon reads as part of the sentence, not a lighter artefact.
//
// SIZE IS A CLOSED SET, not a className. Sizing used to be passed as
// "w-4 h-4" per call site and drifted to eight different values, one of which
// (w-4.5) Tailwind does not generate at all -- it emitted no CSS, so Track's
// star ratings rendered with no width for months without anyone noticing.
// A token cannot silently produce nothing: pass a bad one and tsc fails.
//
// className is for COLOUR and layout only. Passing w-/h- through it still
// works if something genuinely needs an odd size, but it is now the exception
// that has to be argued for rather than the default path.
//
// The steps are tied to what they sit next to:
//   xs 14  inline with text-xs / [11px] micro labels
//   sm 16  inline with text-sm and base -- the default, ~85% of uses
//   md 20  standalone controls, bottom nav
//   lg 24  section headings, list avatars
//   xl 40  empty-state hero
const SIZE = {
  xs: 'w-3.5 h-3.5', sm: 'w-4 h-4', md: 'w-5 h-5', lg: 'w-6 h-6', xl: 'w-10 h-10',
} as const

export type IconSize = keyof typeof SIZE

// \`filled\` is typed against FilledIconName, so passing it to an icon with no
// fill variant is a compile error rather than a silent fall back to the bold
// path -- same reasoning as the size tokens.
type IconProps = { size?: IconSize; className?: string } & (
  | { name: IconName; filled?: false }
  | { name: FilledIconName; filled: true }
)

export default function Icon({ name, size = 'sm', filled = false, className = '' }: IconProps) {
  const d = filled ? FILL[name as FilledIconName] : BOLD[name]
  return (
    <svg viewBox="0 0 256 256" aria-hidden="true"
      className={\`\${SIZE[size]} \${className}\`}>
      <path d={d} fill="currentColor" />
    </svg>
  )
}`)

writeFileSync(OUT, lines.join('\n') + '\n')
console.log(`${OUT}: ${MAP.length} icons x bold only, tokenised sizes`)
