#!/usr/bin/env node
// Regenerate src/components/Icon.tsx from @phosphor-icons/core.
//
//   npm i -D @phosphor-icons/core     # if it is not installed
//   npm run build:icons
//
// WHY GENERATE RATHER THAN IMPORT. @phosphor-icons/react would be the obvious
// choice, but it ships a React component per icon and this app already sits over
// Vite's bundle-size warning -- the page-weight work took the entry from 5,161 kB
// to 821 kB and it is not worth giving any of that back for 22 shapes. Inlining
// the path data keeps the runtime dependency at zero and the CDN request count
// at zero, which is what the previous Font Awesome file did too.
//
// TO ADD AN ICON: put it in MAP below with its Phosphor name, run this, commit
// the regenerated Icon.tsx. The script fails loudly if a name does not exist in
// both weights rather than silently emitting a broken glyph.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'

const A = 'node_modules/@phosphor-icons/core/assets'
const OUT = 'src/components/Icon.tsx'

// our name -> phosphor name. Two are deliberate reinterpretations, not renames:
//   boxOpen       -> package      a parcel, which is what a pickup errand is
//   rectangleList -> list-dashes  a list of items, not a bulleted paragraph
const MAP = [
  ['forkKnife', 'fork-knife'], ['boxOpen', 'package'], ['bagShopping', 'shopping-bag'],
  ['receipt', 'receipt'], ['magnifyingGlass', 'magnifying-glass'], ['locationDot', 'map-pin'],
  ['star', 'star'], ['clock', 'clock'], ['minus', 'minus'], ['plus', 'plus'],
  ['clone', 'copy'], ['moneyBill', 'money'], ['mobileScreen', 'device-mobile'],
  ['house', 'house'], ['rectangleList', 'list-dashes'], ['penToSquare', 'note-pencil'],
  ['creditCard', 'credit-card'], ['cartShopping', 'shopping-cart'], ['chevronLeft', 'caret-left'],
  ['truck', 'truck'], ['tag', 'tag'], ['circleUser', 'user-circle'],
  ['check', 'check'], ['x', 'x'], ['warning', 'warning'],
  ['pill', 'pill'], ['moped', 'moped-front'], ['repeat', 'repeat'],
  ['envelope', 'envelope'], ['chatCircle', 'chat-circle'], ['broadcast', 'broadcast'],
  ['paperclip', 'paperclip'], ['arrowUp', 'arrow-up'], ['image', 'image'],
  ['briefcase', 'briefcase'], ['wallet', 'wallet'], ['clipboardText', 'clipboard-text'],
  ['bell', 'bell'], ['phone', 'phone'], ['thumbsDown', 'thumbs-down'],
  ['question', 'question'], ['camera', 'camera'], ['coins', 'coins'],
  ['arrowCounterClockwise', 'arrow-counter-clockwise'], ['pencilSimple', 'pencil-simple'],
  ['arrowRight', 'arrow-right'], ['user', 'user'],
  ['hourglass', 'hourglass'], ['flask', 'flask'], ['van', 'van'], ['moon', 'moon'],
  ['gear', 'gear'], ['arrowUturn', 'arrow-u-up-left'], ['megaphone', 'megaphone'],
  ['storefront', 'storefront'], ['speakerSlash', 'speaker-slash'], ['link', 'link'],
  ['chartLineDown', 'chart-line-down'], ['arrowDown', 'arrow-down'], ['trash', 'trash'],
  ['folders', 'folders'], ['bellRinging', 'bell-ringing'], ['siren', 'siren'],
  ['mobileSlash', 'device-mobile-slash'], ['handPointing', 'hand-pointing'], ['car', 'car'],
  ['trafficSignal', 'traffic-signal'], ['users', 'users'], ['chartBar', 'chart-bar'],
  ['thumbsUp', 'thumbs-up'], ['prohibit', 'prohibit'], ['note', 'note'],
  ['stethoscope', 'stethoscope'], ['handSoap', 'hand-soap'], ['basket', 'basket'],
  ['sprayBottle', 'spray-bottle'], ['umbrella', 'umbrella-simple'],
  ['baby', 'baby'], ['carrot', 'carrot'], ['cheese', 'cheese'],
]

if (!existsSync(A)) {
  console.error(`${A} not found. Run:  npm i -D @phosphor-icons/core`)
  process.exit(2)
}

/** Phosphor emits one <path> per icon. More than one means the shape would be
 *  clipped if we only took the first, so refuse rather than emit it. */
function pathOf(file, label) {
  if (!existsSync(file)) { console.error(`missing: ${label} (${file})`); process.exit(1) }
  const found = [...readFileSync(file, 'utf8').matchAll(/<path\s+d="([^"]+)"/g)].map(m => m[1])
  if (found.length !== 1) {
    console.error(`${label} has ${found.length} paths; this generator assumes exactly 1`)
    process.exit(1)
  }
  return found[0]
}

const names = MAP.map(([n]) => n)
const lines = []
lines.push(`// GENERATED by scripts/build-icons.mjs from @phosphor-icons/core. Do not edit by
// hand -- add to MAP in that script and re-run instead.
//
// Path data is inlined so there is no runtime dependency and no CDN request.
// Phosphor draws every icon on a 256x256 grid, so they are all optically the
// same size at the same className; the previous Font Awesome set used a
// per-icon viewBox and was not.
//
// Both weights are complete for all 1,512 Phosphor icons, so \`variant\` is a real
// choice. Under Font Awesome Free it was not: only a handful of shapes had an
// outline, so variant="regular" silently fell back to solid and active states
// had to lean on colour alone -- which is what fails for a colour-blind operator.`)
lines.push('')
lines.push('export type IconName =')
for (let i = 0; i < names.length; i += 4) {
  lines.push((i ? '  | ' : '  ') + names.slice(i, i + 4).map(n => `'${n}'`).join(' | '))
}
lines.push('')
for (const [weight, konst, suffix] of [['bold', 'BOLD', '-bold']]) {
  lines.push('')
  lines.push(`const ${konst}: Record<IconName, string> = {`)
  for (const [our, ph] of MAP) {
    lines.push(`  ${our}: '${pathOf(`${A}/${weight}/${ph}${suffix}.svg`, `${our} (${weight})`)}',`)
  }
  lines.push('}')
}
lines.push(`
// Bold weight, not regular: at the 16-20px these render at, regular's hairlines
// go muddy next to IBM Plex Sans Arabic's stems. Bold matches the text colour
// weight so an icon reads as part of the sentence, not a lighter artefact.
//
// The 2px inset is baked in here rather than left to call sites, because a
// frame that is only sometimes applied is worse than none -- icons would sit
// at two different optical sizes across screens. className sets the OUTER box;
// box-border keeps w-4 h-4 meaning 16px total, glyph 12px inside it.
// Only the bold weight is generated. Phosphor ships six, and an earlier pass
// emitted 'fill' too -- but nothing ever set variant="fill", so it was ~7kB of
// dead paths in every bundle. Adding a weight back is one entry in the loop in
// scripts/build-icons.mjs, so this is cheap to undo the day a filled state is
// actually wanted.
export default function Icon({ name, className = '' }: {
  name: IconName; className?: string
}) {
  const d = BOLD[name]
  return (
    <svg viewBox="0 0 256 256" aria-hidden="true"
      className={\`box-border p-[2px] \${className}\`}>
      <path d={d} fill="currentColor" />
    </svg>
  )
}`)

writeFileSync(OUT, lines.join('\n') + '\n')
console.log(`${OUT}: ${MAP.length} icons x bold only, 2px inset`)
