
UPDATE compounds AS c SET name_en = v.name_en
FROM (VALUES
(3,'Mountain View Sokhna'),
(7,'La Sirena Palm Beach Resort'),
(8,'La Vista 1'),
(10,'La Vista 3'),
(11,'La Vista 4'),
(12,'La Vista 5'),
(13,'Coronado'),
(17,'Coral Sea Beach & Aqua Park Resort'),
(22,'Piacera'),
(23,'Kai Sokhna'),
(24,'Telal Ain Sokhna'),
(32,'Grand Ocean Sokhna Hotel'),
(43,'Dome Marina Hotel'),
(44,'Bella Vento Galala'),
(45,'Tolip Galala Hills'),
(46,'Baymount Sokhna'),
(47,'Il Monte Galala'),
(48,'La Vista 6'),
(50,'Hijaz Oasis Resort (Al Hejaz 3)'),
(52,'Sokhna Hills Resort'),
(53,'Laguna'),
(62,'New Venesia'),
(63,'La Siesta Hotel El Sokhna'),
(65,'Jebal Resort'),
(66,'Viva El Sokhna Resort'),
(68,'The Groove Sokhna'),
(70,'Moon View Beach Resort'),
(71,'Porto South Beach Sokhna'),
(72,'Areej Resort'),
(73,'La Vista Gardens'),
(74,'Heaven Beach (Misr Sinien)'),
(75,'Fanar De Luna Resort'),
(76,'BOHO Sokhna'),
(78,'Venecia Resort Ain Sokhna'),
(80,'Orlando 2 Aquapark Ain Sokhna'),
(81,'Coronado Beach Resort'),
(82,'La Vista 7'),
(93,'Porto Sokhna - Pyramids'),
(94,'Porto Sokhna - Hawaiian'),
(95,'Porto Sokhna - Caribbean'),
(97,'Golf Bay - Porto El Sokhna'),
(98,'Porto Sokhna - Waterfront'),
(100,'Porto Sokhna - Panorama'),
(101,'Porto Sokhna - Hanging Gardens'),
(104,'Galala City'),
(117,'Dolphin Beach Ain Sokhna'),
(118,'Loly Beach'),
(120,'Murano Resort'),
(122,'Blumar El Dome'),
(124,'La Vista Topaz'),
(142,'Empire Resort'),
(143,'Coronado Beach Resort (El Nagma)'),
(144,'Mountain View Sokhna'),
(145,'Orlando 1 Resort'),
(147,'Venecia Resort (Zaafarana)'),
(148,'La Sirena Resort'),
(150,'Romance Beach Hotel'),
(151,'Piacera Resort'),
(152,'La Vista 3 (Zaafarana)'),
(153,'La Vista 4 (Zaafarana)'),
(154,'La Vista 5 (Zaafarana)'),
(155,'La Vista 7 (Zaafarana)'),
(156,'La Vista Ray'),
(157,'La Vista Gardens (Zaafarana)'),
(158,'Stella Di Mare Sea View 2'),
(165,'Amexco Paradise (Mexico Paradise)'),
(166,'Blue Blue Ain Sokhna'),
(167,'Cancun Sokhna Resort & Villas'),
(168,'La Vista 6')
) AS v(id, name_en)
WHERE c.id = v.id;
