
UPDATE compounds AS c SET name = v.name_ar, name_en = v.name_en
FROM (VALUES
(3,'Mountain View Sokhna 2','Mountain View Sokhna 2'),
(7,'La Sirena Palm Beach Resort','La Sirena Palm Beach Resort'),
(8,'La Vista 1','La Vista 1'),
(10,'La Vista 3','La Vista 3'),
(11,'La Vista 4','La Vista 4'),
(12,'La Vista 5','La Vista 5'),
(13,'Coronado','Coronado'),
(17,'Coral Sea Beach & Aqua Park Resort','Coral Sea Beach & Aqua Park Resort'),
(22,'Piacera Resort','Piacera Resort'),
(23,'Kai Sokhna','Kai Sokhna'),
(24,'Telal Ain Sokhna','Telal Ain Sokhna'),
(32,'Grand Ocean Sokhna Hotel','Grand Ocean Sokhna Hotel'),
(43,'Dome Marina Hotel','Dome Marina Hotel'),
(44,'Bella Vento Galala','Bella Vento Galala'),
(45,'Tolip Resort Elgalala Hills','Tolip Resort Elgalala Hills'),
(46,'Baymount Sokhna','Baymount Sokhna'),
(47,'Il Monte Galala','Il Monte Galala'),
(48,'La Vista 6','La Vista 6'),
(50,'Hijaz Oasis Resort','Hijaz Oasis Resort'),
(52,'Sokhna Hills Resort','Sokhna Hills Resort'),
(53,'Laguna','Laguna'),
(62,'New Venesia','New Venesia'),
(63,'La Siesta Hotel El Sokhna','La Siesta Hotel El Sokhna'),
(65,'Jebal Resort','Jebal Resort'),
(66,'Viva El Sokhna Resort','Viva El Sokhna Resort'),
(68,'The Groove Sokhna','The Groove Sokhna'),
(70,'Moon View Beach Resort','Moon View Beach Resort'),
(71,'بورتو ساوث بيتش السويس','Porto South Beach Sokhna'),
(72,'Areej','Areej'),
(73,'La Vista Gardens','La Vista Gardens'),
(74,'Heaven Beach (Misr Sinien)','Heaven Beach (Misr Sinien)'),
(75,'Fanar De Luna Resort','Fanar De Luna Resort'),
(76,'BOHO Sokhna','BOHO Sokhna'),
(78,'Venecia Resort Ain Sokhna','Venecia Resort Ain Sokhna'),
(80,'منتجع اورلاندو 2 اكوابارك العين السخنة','Orlando 2 Aquapark Ain Sokhna'),
(81,'Coronado Beach Resort','Coronado Beach Resort'),
(82,'La Vista 7','La Vista 7'),
(93,'Pyramids Porto Sokhna Families Only','Pyramids Porto Sokhna Families Only'),
(94,'Porto Sokhna - Hawaian','Porto Sokhna - Hawaiian'),
(95,'بورتو كريبيان العين السخنه','Porto Caribbean Ain Sokhna'),
(97,'Golf Bay Porto El Sokhna','Golf Bay Porto El Sokhna'),
(98,'Porto Sokhna - Water front','Porto Sokhna - Waterfront'),
(100,'Panorama Porto El Sokhna','Panorama Porto El Sokhna'),
(101,'Hanging Gardens - Porto Sokhna','Hanging Gardens - Porto Sokhna'),
(104,'Galala City','Galala City'),
(117,'Dolphin Beach Ein Sokhna','Dolphin Beach Ein Sokhna'),
(118,'Loly Beach','Loly Beach'),
(120,'Murano Resort','Murano Resort'),
(122,'Blumar El Dome','Blumar El Dome'),
(124,'La Vista Topaz','La Vista Topaz'),
(142,'Empire Resort','Empire Resort'),
(143,'Coronado Beach Resort','Coronado Beach Resort'),
(144,'Mountain View Sokhna 2','Mountain View Sokhna 2'),
(145,'Orlando','Orlando'),
(147,'Venecia Resort Ain Sokhna','Venecia Resort Ain Sokhna'),
(148,'La Sirena Resort','La Sirena Resort'),
(150,'Romance Beach Hotel','Romance Beach Hotel'),
(151,'Piacera Resort','Piacera Resort'),
(152,'La Vista 3','La Vista 3'),
(153,'La Vista 4','La Vista 4'),
(154,'La Vista 5','La Vista 5'),
(155,'La Vista 7','La Vista 7'),
(156,'La Vista Ray','La Vista Ray'),
(157,'La Vista Gardens','La Vista Gardens'),
(158,'Stella Di Mare Sea View 2','Stella Di Mare Sea View 2'),
(165,'Amexco Paradise','Amexco Paradise'),
(166,'Blue Blue Ain Sokhna','Blue Blue Ain Sokhna'),
(167,'Cancun Sokhna Resort & Villas','Cancun Sokhna Resort & Villas'),
(168,'La Vista 6','La Vista 6')
) AS v(id, name_ar, name_en)
WHERE c.id = v.id;
