create schema if not exists private; revoke all on schema private from public;
alter function public.admin_assign_order(integer,integer,boolean) set schema private;
alter function public.admin_force_delivered(integer,text,boolean) set schema private;
alter function public.admin_reassign_order(integer,integer,text) set schema private;
alter function public.admin_resolve_no_answer(integer,text) set schema private;
alter function public.admin_unassign_order(integer,text) set schema private;
alter function public.mark_delivery_failed(integer) set schema private;
alter function public.staff_create_pickup_order(integer,text,text,integer,text,text,numeric,text) set schema private;
alter function private.admin_reassign_order(integer,integer,text) set search_path to 'private','public';
alter function private.admin_resolve_no_answer(integer,text) set search_path to 'private','public';
revoke all on function private.admin_assign_order(integer,integer,boolean),private.admin_force_delivered(integer,text,boolean),private.admin_reassign_order(integer,integer,text),private.admin_resolve_no_answer(integer,text),private.admin_unassign_order(integer,text),private.mark_delivery_failed(integer),private.staff_create_pickup_order(integer,text,text,integer,text,text,numeric,text) from public,anon,authenticated;

create function public.admin_assign_order(p_order_id integer,p_driver_id integer,p_force boolean default false,p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.admin_assign_order(p_order_id,p_driver_id,p_force);end$f$;
create function public.admin_force_delivered(p_order_id integer,p_reason text,p_cash_collected boolean default true,p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.admin_force_delivered(p_order_id,p_reason,p_cash_collected);end$f$;
create function public.admin_reassign_order(p_order_id integer,p_driver_id integer,p_reason text default 'admin_reassigned',p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.admin_reassign_order(p_order_id,p_driver_id,p_reason);end$f$;
create function public.admin_resolve_no_answer(p_assignment_id integer,p_action text,p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.admin_resolve_no_answer(p_assignment_id,p_action);end$f$;
create function public.admin_unassign_order(p_order_id integer,p_reason text default 'admin_unassigned',p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.admin_unassign_order(p_order_id,p_reason);end$f$;
create function public.mark_delivery_failed(p_assignment_id integer,p_auth_user_id uuid default null) returns void language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);perform private.mark_delivery_failed(p_assignment_id);end$f$;
create function public.staff_create_pickup_order(p_restaurant_id integer,p_customer_name text,p_customer_phone text,p_compound_id integer,p_unit_number text,p_address_notes text default '',p_collect_amount numeric default 0,p_request_notes text default '',p_auth_user_id uuid default null) returns json language plpgsql security definer set search_path='public' as $f$begin perform set_config('request.jwt.claim.sub',p_auth_user_id::text,true);return private.staff_create_pickup_order(p_restaurant_id,p_customer_name,p_customer_phone,p_compound_id,p_unit_number,p_address_notes,p_collect_amount,p_request_notes);end$f$;

revoke all on function public.admin_assign_order(integer,integer,boolean,uuid),public.admin_force_delivered(integer,text,boolean,uuid),public.admin_reassign_order(integer,integer,text,uuid),public.admin_resolve_no_answer(integer,text,uuid),public.admin_unassign_order(integer,text,uuid),public.mark_delivery_failed(integer,uuid),public.staff_create_pickup_order(integer,text,text,integer,text,text,numeric,text,uuid) from public,anon,authenticated;
grant execute on function public.admin_assign_order(integer,integer,boolean,uuid),public.admin_force_delivered(integer,text,boolean,uuid),public.admin_reassign_order(integer,integer,text,uuid),public.admin_resolve_no_answer(integer,text,uuid),public.admin_unassign_order(integer,text,uuid),public.mark_delivery_failed(integer,uuid),public.staff_create_pickup_order(integer,text,text,integer,text,text,numeric,text,uuid) to service_role;

do $v$declare s text;begin foreach s in array array['public.admin_assign_order(integer,integer,boolean,uuid)','public.admin_force_delivered(integer,text,boolean,uuid)','public.admin_reassign_order(integer,integer,text,uuid)','public.admin_resolve_no_answer(integer,text,uuid)','public.admin_unassign_order(integer,text,uuid)','public.mark_delivery_failed(integer,uuid)','public.staff_create_pickup_order(integer,text,text,integer,text,text,numeric,text,uuid)'] loop if has_function_privilege('authenticated',s,'execute') or not has_function_privilege('service_role',s,'execute') then raise exception 'invalid dispatch wrapper privilege %',s;end if;end loop;end$v$;
