-- Reusable kitchen pickup locations and per-destination delivery-fee overrides.
-- Empty override means "use the normal compound fee".
-- This migration does not change any existing fee until an admin saves an override.

create table if not exists public.restaurant_kitchens (
  id bigint generated by default as identity primary key,
  restaurant_id integer not null references public.restaurants(id) on delete cascade,
  name text not null check (char_length(btrim(name)) between 2 and 120),
  address text,
  latitude numeric,
  longitude numeric,
  active boolean not null default true,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists restaurant_kitchens_one_default
  on public.restaurant_kitchens (restaurant_id) where is_default;
create index if not exists restaurant_kitchens_restaurant_active_idx
  on public.restaurant_kitchens (restaurant_id, active);

create table if not exists public.kitchen_compound_fees (
  kitchen_id bigint not null references public.restaurant_kitchens(id) on delete cascade,
  compound_id integer not null references public.compounds(id) on delete cascade,
  delivery_fee numeric check (delivery_fee is null or delivery_fee >= 0),
  updated_at timestamptz not null default now(),
  primary key (kitchen_id, compound_id)
);
create index if not exists kitchen_compound_fees_compound_idx
  on public.kitchen_compound_fees (compound_id);

alter table public.restaurant_kitchens enable row level security;
alter table public.kitchen_compound_fees enable row level security;
revoke all on public.restaurant_kitchens from anon, authenticated;
revoke all on public.kitchen_compound_fees from anon, authenticated;
grant select, insert, update, delete on public.restaurant_kitchens to authenticated;
grant select, insert, update, delete on public.kitchen_compound_fees to authenticated;
grant usage, select on sequence public.restaurant_kitchens_id_seq to authenticated;

drop policy if exists restaurant_kitchens_admin_only on public.restaurant_kitchens;
create policy restaurant_kitchens_admin_only on public.restaurant_kitchens for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists kitchen_compound_fees_admin_only on public.kitchen_compound_fees;
create policy kitchen_compound_fees_admin_only on public.kitchen_compound_fees for all to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

-- The active default kitchen can override a destination; otherwise default to
-- the existing compound fee. Availability remains controlled by vendor coverage.
create or replace function private.delivery_fee_for_restaurant(p_restaurant_id integer, p_compound_id integer)
returns numeric language sql stable security definer set search_path = public, private as $$
  select coalesce(
    (select kcf.delivery_fee
       from public.restaurant_kitchens k
       join public.kitchen_compound_fees kcf on kcf.kitchen_id = k.id
      where k.restaurant_id = p_restaurant_id and k.active and k.is_default
        and kcf.compound_id = p_compound_id and kcf.delivery_fee is not null
      limit 1),
    (select c.delivery_fee from public.compounds c where c.id = p_compound_id)
  );
$$;
revoke all on function private.delivery_fee_for_restaurant(integer, integer) from public, anon, authenticated;

create or replace function public.delivery_quote(p_compound_id integer, p_restaurant_id integer default null)
returns json language sql stable security definer set search_path = public, private as $$
  select json_build_object(
    'compound_id', c.id, 'compound_name', c.name, 'distance_km', c.distance_km,
    'delivery_fee', case when p_restaurant_id is null then c.delivery_fee
                         else private.delivery_fee_for_restaurant(p_restaurant_id, c.id) end,
    'sla_minutes', public.sla_minutes_for(p_restaurant_id, c.id),
    'sla_max_minutes', public.sla_max_minutes(public.sla_minutes_for(p_restaurant_id, c.id)),
    'prep_minutes', coalesce((select r.prep_minutes from public.restaurants r where r.id = p_restaurant_id), 20),
    'travel_minutes', public.travel_minutes_for_compound(c.id)
  )
  from public.compounds c where c.id = p_compound_id;
$$;

-- Patch the three server-owned creation paths; client-supplied delivery_fee is
-- never trusted. The assertion prevents a partial rollout if a source changed.
do $$
declare r record; v_definition text;
  v_old text := 'select distance_km, delivery_fee into v_km, v_fee from compounds where id = p_compound_id;';
  v_new text := 'select distance_km into v_km from compounds where id = p_compound_id;' || chr(10) ||
                '  v_fee := private.delivery_fee_for_restaurant(p_restaurant_id, p_compound_id);';
  v_patched integer := 0;
begin
  for r in select p.oid from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='private' and p.proname in ('place_order','request_pickup','submit_custom_order')
  loop
    v_definition := pg_get_functiondef(r.oid);
    if position(v_old in v_definition)=0 then
      raise exception 'Expected compound fee lookup was not found in private function %', r.oid;
    end if;
    execute replace(v_definition, v_old, v_new);
    v_patched := v_patched + 1;
  end loop;
  if v_patched <> 3 then raise exception 'Expected to patch 3 order-creation functions, patched %', v_patched; end if;
end $$;
