-- Quote acceptance state machine — complete local implementation draft.
--
-- LOCAL DRAFT: do not apply until its transition functions, RLS policies,
-- Edge Function changes, and test evidence have been reviewed together.
--
-- This migration is intentionally additive. It does not reinterpret legacy
-- pricing_status = 'confirmed' as customer consent and it does not change any
-- existing order's operational or payment state.

create table if not exists public.order_quotes (
  id bigint generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete restrict,
  version integer not null,
  state text not null,
  issued_by uuid references auth.users(id) on delete set null,
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references auth.users(id) on delete set null,
  rejected_at timestamptz,
  rejected_by uuid references auth.users(id) on delete set null,
  reminder_sent_at timestamptz,
  rejection_reason text,
  subtotal numeric not null check (subtotal >= 0),
  delivery_fee numeric not null check (delivery_fee >= 0),
  service_fee numeric not null default 0 check (service_fee >= 0),
  promo_code_id integer references public.promo_codes(id) on delete set null,
  promo_discount numeric not null default 0 check (promo_discount >= 0),
  promo_discount_service numeric not null default 0 check (promo_discount_service >= 0),
  promo_discount_delivery numeric not null default 0 check (promo_discount_delivery >= 0),
  promo_discount_vendor numeric not null default 0 check (promo_discount_vendor >= 0),
  wallet_used numeric not null default 0 check (wallet_used >= 0),
  total numeric not null check (total >= 0),
  payment_method text,
  deposit_required boolean not null default false,
  deposit_amount numeric not null default 0 check (deposit_amount >= 0),
  currency text not null default 'EGP' check (currency = 'EGP'),
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  constraint order_quotes_state_check
    check (state in ('offered', 'accepted', 'rejected', 'expired', 'superseded')),
  constraint order_quotes_version_unique unique (order_id, version),
  constraint order_quotes_issue_idempotency_unique unique (order_id, idempotency_key),
  constraint order_quotes_expiry_after_issue check (expires_at > issued_at),
  constraint order_quotes_response_consistency check (
    (state = 'accepted' and accepted_at is not null
      and rejected_at is null and rejected_by is null)
    or (state = 'rejected' and rejected_at is not null
      and accepted_at is null and accepted_by is null)
    or (state in ('offered', 'expired', 'superseded')
      and accepted_at is null and accepted_by is null
      and rejected_at is null and rejected_by is null)
  ),
  constraint order_quotes_deposit_bound check (deposit_amount <= total)
);

create unique index if not exists order_quotes_one_current_offer_per_order
  on public.order_quotes(order_id)
  where state = 'offered';

-- The primary key makes `id` unique, but the composite unique key lets the
-- orders row prove that its current_quote_id belongs to the same order.
alter table public.order_quotes
  drop constraint if exists order_quotes_id_order_id_unique,
  add constraint order_quotes_id_order_id_unique unique (id, order_id);

create index if not exists order_quotes_expiry_sweep_idx
  on public.order_quotes(expires_at)
  where state = 'offered';

-- The existing order_status_events table remains the compatibility feed for
-- legacy portals. This ledger is the canonical, append-only record for state
-- dimensions and financial decisions; it never overwrites a prior event.
create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete restrict,
  event_type text not null,
  state_dimension text,
  before_state jsonb,
  after_state jsonb,
  actor_role text not null,
  actor_uid uuid references auth.users(id) on delete set null,
  reason text,
  correlation_id uuid,
  idempotency_key uuid,
  created_at timestamptz not null default now(),
  constraint order_events_dimension_check check (state_dimension is null or state_dimension in (
    'commercial', 'quote', 'payment', 'fulfilment', 'delivery', 'exception'
  ))
);

create unique index if not exists order_events_idempotency_unique
  on public.order_events(order_id, event_type, idempotency_key)
  where idempotency_key is not null;
create index if not exists order_events_order_created_idx
  on public.order_events(order_id, created_at desc);

alter table public.order_events enable row level security;

-- Once quote acceptance exists, the legacy direct-confirmation RPC must not
-- remain callable by an older Edge Function. A failed legacy call is safe; a
-- silently advanced order is not.
revoke all on function public.confirm_custom_order_price(integer,numeric,uuid) from service_role;

alter table public.orders
  add column if not exists quote_state text,
  add column if not exists current_quote_id bigint references public.order_quotes(id) on delete restrict;

alter table public.orders
  drop constraint if exists orders_quote_state_check;

alter table public.orders
  add constraint orders_quote_state_check
  check (quote_state is null or quote_state in (
    'not_required', 'pending', 'offered', 'accepted', 'rejected', 'expired', 'superseded'
  ));

-- Quotes at or below this total can be issued by a Supervisor. A larger quote
-- needs an Admin decision. It is a Class-A numeric policy, not a client-side
-- limit, so it is safe to adjust through settings without changing code.
insert into public.settings (key, value, label, kind, required, min_value, max_value)
values (
  'quote_admin_approval_ceiling_egp', '3000',
  'أقصى إجمالي عرض يرسله المشرف بدون موافقة الإدارة (ج.م)',
  'numeric', true, 0, 1000000
)
on conflict (key) do nothing;

alter table public.orders
  drop constraint if exists orders_current_quote_matches_order_fk,
  add constraint orders_current_quote_matches_order_fk
    foreign key (current_quote_id, id)
    references public.order_quotes(id, order_id)
    on delete restrict;

-- Legacy compatibility only. A historical `confirmed` price was confirmed by
-- staff, not accepted by a customer, and therefore deliberately remains NULL.
update public.orders
set quote_state = case
  when order_type = 'catalog' then 'not_required'
  when order_type = 'custom_request' and pricing_status = 'pending_quote' then 'pending'
  else null
end
where quote_state is null;

-- The compatibility backfill above intentionally leaves historical
-- staff-confirmed custom orders NULL. New orders, however, must begin with a
-- canonical quote state as soon as this migration is active.
create or replace function private.initialize_order_quote_state()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  -- A customer authenticated through Supabase Auth may not carry the legacy
  -- customer-session token. The public order wrapper has already established
  -- the authenticated subject in that case, so bind the new custom order to
  -- that account rather than making its history disappear from My Orders.
  if new.customer_id is null and new.order_type = 'custom_request' then
    new.customer_id := my_customer_id();
  end if;
  if new.quote_state is null then
    if new.order_type = 'catalog' then
      new.quote_state := 'not_required';
    elsif new.order_type = 'custom_request' then
      new.quote_state := 'pending';
    end if;
  end if;
  return new;
end;
$function$;

drop trigger if exists initialize_order_quote_state on public.orders;
create trigger initialize_order_quote_state
before insert on public.orders
for each row execute function private.initialize_order_quote_state();

alter table public.order_quotes enable row level security;

-- No public table policies are added here. Quote reads and decisions must first
-- be routed through customer-authenticated database functions, which will be
-- introduced with the Edge Function implementation. Leaving the new table
-- default-deny prevents accidental client exposure while that work is pending.

-- Vendors previously read every order belonging to their restaurant, including
-- unpriced custom requests. Keep staff, supervisor, and driver visibility
-- unchanged, but let a vendor see a custom request only after its quote has
-- been accepted and any required payment is no longer pending. Historical
-- staff-confirmed custom orders intentionally retain quote_state NULL during
-- rollout, so their pre-existing visibility is preserved.
drop policy if exists "read orders" on public.orders;
create policy "read orders" on public.orders for select
  using (
    is_admin()
    or exists (select 1 from delivery_assignments da where da.order_id = orders.id and da.driver_id = my_driver_id())
    or supervisor_may_touch_order(id)
    or (
      restaurant_id = my_restaurant_id()
      and (
        order_type <> 'custom_request'
        or (quote_state is null and status <> 'awaiting_payment')
        or (quote_state = 'accepted' and status <> 'awaiting_payment')
      )
    )
  );

drop policy if exists "read order items" on public.order_items;
create policy "read order items" on public.order_items for select
  using (
    is_admin()
    or exists (select 1 from delivery_assignments da where da.order_id = order_items.order_id and da.driver_id = my_driver_id())
    or (is_supervisor() and exists (select 1 from orders o where o.id = order_items.order_id))
    or exists (
      select 1 from orders o
       where o.id = order_items.order_id
         and o.restaurant_id = my_restaurant_id()
         and (
           o.order_type <> 'custom_request'
           or (o.quote_state is null and o.status <> 'awaiting_payment')
           or (o.quote_state = 'accepted' and o.status <> 'awaiting_payment')
         )
    )
  );

-- Both customer history paths return JSON rather than generated table types.
-- Include the canonical quote state so a list never presents an offered quote
-- as a final total, while retaining the legacy pricing field for old clients.
create or replace function private.my_customer_orders()
returns json
language sql
stable
security definer
set search_path to 'public'
as $function$
  select coalesce(json_agg(row_to_json(x)), '[]'::json) from (
    select o.id, o.public_token, o.total, o.status, o.created_at,
           coalesce(o.pricing_status, 'n/a') as pricing_status,
           o.quote_state, r.name as restaurant_name
      from orders o join restaurants r on r.id = o.restaurant_id
     where o.customer_id = my_customer_id()
       and o.created_at > now() - interval '90 days'
     order by o.id desc limit 30
  ) x;
$function$;

create or replace function public.my_orders(
  p_phone text, p_session_token uuid, p_auth_user_id uuid
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_phone text;
begin
  if p_session_token is not null then
    select c.phone into v_phone
      from customer_sessions cs join customers c on c.id = cs.customer_id
     where cs.token = p_session_token and cs.expires_at > now();
  end if;
  if v_phone is null and p_auth_user_id is not null then
    select c.phone into v_phone from customers c
     where c.auth_user_id = p_auth_user_id and coalesce(c.phone, '') <> '' limit 1;
  end if;
  if v_phone is null then raise exception 'not_logged_in'; end if;
  v_phone := normalize_phone(v_phone);
  return (
    select coalesce(json_agg(row_to_json(x)), '[]'::json)
      from (
        select o.id, o.public_token, o.total, o.status, o.created_at,
               coalesce(o.pricing_status, 'n/a') as pricing_status,
               o.quote_state, r.name as restaurant_name
          from orders o join restaurants r on r.id = o.restaurant_id
         where normalize_phone(o.customer_phone) = v_phone
           and o.created_at > now() - interval '30 days'
         order by o.id desc limit 20
      ) x
  );
end;
$function$;

-- Pure quote calculator. Unlike private.reprice_order(), this function makes no
-- writes to orders, wallets, redemptions, or events. The issue transition will
-- call it while holding the order lock, then store its result as an immutable
-- quote snapshot. Acceptance—not quotation—is responsible for ledger effects.
create or replace function private.custom_order_quote_snapshot(
  p_order_id integer,
  p_subtotal numeric
)
returns table (
  subtotal numeric,
  delivery_fee numeric,
  service_fee numeric,
  promo_code_id integer,
  promo_discount numeric,
  promo_discount_service numeric,
  promo_discount_delivery numeric,
  promo_discount_vendor numeric,
  wallet_used numeric,
  total numeric,
  payment_method text,
  deposit_required boolean,
  deposit_amount numeric
)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_order orders%rowtype;
  v_promo promo_codes%rowtype;
  v_service numeric;
  v_discount numeric := 0;
  v_discount_service numeric := 0;
  v_discount_delivery numeric := 0;
  v_discount_vendor numeric := 0;
  v_total numeric;
  v_wallet numeric;
  v_deposit numeric := 0;
begin
  if p_subtotal is null or p_subtotal < 0 then raise exception 'invalid_amount'; end if;

  select * into v_order
    from orders
   where id = p_order_id and order_type = 'custom_request';
  if not found then raise exception 'order_not_found'; end if;
  if v_order.status = 'Cancelled' then raise exception 'order_closed'; end if;

  v_service := round(p_subtotal * private.setting_num('service_fee_percent') / 100.0);

  if v_order.promo_code_id is not null then
    select * into v_promo from promo_codes where id = v_order.promo_code_id;
    if found then
      v_discount := private.promo_discount_for(
        v_promo, p_subtotal, coalesce(v_order.delivery_fee, 0), v_service);
      select cut_service, cut_delivery, cut_vendor
        into v_discount_service, v_discount_delivery, v_discount_vendor
        from private.promo_split(
          v_promo.applies_to, v_discount, coalesce(v_order.delivery_fee, 0), v_service);
    end if;
  end if;

  v_total := greatest(0, p_subtotal + coalesce(v_order.delivery_fee, 0) + v_service - v_discount);
  v_wallet := least(coalesce(v_order.wallet_used, 0), v_total);

  -- orders.total is the net amount due after any wallet contribution. The
  -- deposit threshold and amount must use that same net number.
  v_total := v_total - v_wallet;

  if v_order.payment_method = 'cod'
     and v_total > private.setting_num('cod_deposit_threshold_egp') then
    v_deposit := least(
      ceil(v_total * private.setting_num('cod_deposit_percent') / 100.0),
      v_total
    );
  end if;

  return query select
    p_subtotal,
    coalesce(v_order.delivery_fee, 0),
    v_service,
    v_order.promo_code_id::integer,
    v_discount,
    v_discount_service,
    v_discount_delivery,
    v_discount_vendor,
    v_wallet,
    v_total,
    v_order.payment_method,
    v_deposit > 0,
    v_deposit;
end;
$function$;

-- Customer push is issued by the server so it is delivered while the app is
-- backgrounded or the phone is locked. A failed push must never roll back the
-- quote transition itself.
create or replace function private.notify_quote_customer(
  p_order_id integer, p_quote_id bigint, p_kind text, p_title text, p_body text
)
returns void language plpgsql security definer set search_path to 'public' as $function$
declare v_token text; v_platform text; v_order_token uuid; v_secret text;
begin
  select push_token, coalesce(push_platform, 'web'), public_token
    into v_token, v_platform, v_order_token from orders where id = p_order_id;
  if v_token is null or v_order_token is null then return; end if;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'push_webhook_secret';
  perform net.http_post(
    url := 'https://pqpnwxyevrsipklzmwex.supabase.co/functions/v1/send-push',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-webhook-secret', coalesce(v_secret, '')),
    body := jsonb_build_object(
      'tokens', jsonb_build_array(jsonb_build_object('token', v_token, 'platform', v_platform)),
      'title', p_title, 'body', p_body,
      'data', jsonb_build_object('order_id', p_order_id, 'quote_id', p_quote_id, 'kind', p_kind, 'link', '/track/' || v_order_token)
    )
  );
exception when others then
  return;
end;
$function$;

create or replace function private.record_order_event(
  p_order_id integer, p_event_type text, p_dimension text,
  p_before jsonb, p_after jsonb, p_actor_role text,
  p_reason text default null, p_idempotency_key uuid default null
)
returns void language plpgsql security definer set search_path to 'public' as $function$
begin
  insert into order_events (
    order_id, event_type, state_dimension, before_state, after_state,
    actor_role, actor_uid, reason, idempotency_key
  ) values (
    p_order_id, p_event_type, p_dimension, p_before, p_after,
    p_actor_role, auth.uid(), nullif(trim(coalesce(p_reason, '')), ''), p_idempotency_key
  ) on conflict (order_id, event_type, idempotency_key) where idempotency_key is not null do nothing;
end;
$function$;

-- Issue only creates an offer. It deliberately does not update totals, payment
-- state, vendor visibility, dispatch state, wallet balances, or promo
-- redemptions on the live order.
create or replace function private.issue_custom_order_quote(
  p_order_id integer,
  p_subtotal numeric,
  p_expires_at timestamptz,
  p_idempotency_key uuid
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_order orders%rowtype;
  v_existing order_quotes%rowtype;
  v_snapshot record;
  v_quote_id bigint;
  v_version integer;
  v_expires_at timestamptz;
  v_superseded record;
begin
  if not is_supervisor() then raise exception 'not_authorized'; end if;
  if p_subtotal is null or p_subtotal < 0 then raise exception 'invalid_amount'; end if;
  if p_idempotency_key is null then raise exception 'invalid_idempotency_key'; end if;

  -- Policy is server-owned. The client still sends the intended value for
  -- request-shape compatibility, but it cannot lengthen or shorten the offer.
  v_expires_at := now() + interval '15 minutes';

  select * into v_order
    from orders
   where id = p_order_id and order_type = 'custom_request'
   for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_order.status = 'Cancelled' then raise exception 'order_closed'; end if;
  if coalesce(v_order.quote_state,
       case when v_order.pricing_status = 'pending_quote' then 'pending' end) not in ('pending', 'offered', 'rejected', 'expired') then
    raise exception 'quote_not_pending';
  end if;

  -- A retry returns the original immutable offer; it never creates v2.
  select * into v_existing
    from order_quotes
   where order_id = p_order_id and idempotency_key = p_idempotency_key;
  if found then
    return json_build_object('quote_id', v_existing.id, 'version', v_existing.version, 'state', v_existing.state);
  end if;

  select * into v_snapshot from private.custom_order_quote_snapshot(p_order_id, p_subtotal);

  if not is_admin()
     and v_snapshot.total > private.setting_num('quote_admin_approval_ceiling_egp') then
    raise exception 'quote_requires_admin_approval';
  end if;

  -- A price that has not changed is not a new commercial offer. Returning the
  -- live version avoids resetting the customer's 15-minute decision window or
  -- emitting duplicate “price ready” notifications when staff retry a send.
  select * into v_existing
    from order_quotes
   where order_id = p_order_id and state = 'offered'
   for update;
  if found
     and v_existing.subtotal is not distinct from v_snapshot.subtotal
     and v_existing.delivery_fee is not distinct from v_snapshot.delivery_fee
     and v_existing.service_fee is not distinct from v_snapshot.service_fee
     and v_existing.promo_code_id is not distinct from v_snapshot.promo_code_id
     and v_existing.promo_discount is not distinct from v_snapshot.promo_discount
     and v_existing.promo_discount_service is not distinct from v_snapshot.promo_discount_service
     and v_existing.promo_discount_delivery is not distinct from v_snapshot.promo_discount_delivery
     and v_existing.promo_discount_vendor is not distinct from v_snapshot.promo_discount_vendor
     and v_existing.wallet_used is not distinct from v_snapshot.wallet_used
     and v_existing.total is not distinct from v_snapshot.total
     and v_existing.payment_method is not distinct from v_snapshot.payment_method
     and v_existing.deposit_required is not distinct from v_snapshot.deposit_required
     and v_existing.deposit_amount is not distinct from v_snapshot.deposit_amount then
    return json_build_object('quote_id', v_existing.id, 'version', v_existing.version, 'state', v_existing.state);
  end if;

  for v_superseded in
    update order_quotes
       set state = 'superseded'
     where order_id = p_order_id and state = 'offered'
     returning id
  loop
    perform private.record_order_event(
      p_order_id, 'quote.superseded', 'quote',
      jsonb_build_object('state', 'offered', 'quote_id', v_superseded.id),
      jsonb_build_object('state', 'superseded', 'quote_id', v_superseded.id),
      case when is_admin() then 'admin' else 'supervisor' end, null, p_idempotency_key
    );
  end loop;

  select coalesce(max(version), 0) + 1 into v_version
    from order_quotes where order_id = p_order_id;

  insert into order_quotes (
    order_id, version, state, issued_by, expires_at,
    subtotal, delivery_fee, service_fee, promo_code_id,
    promo_discount, promo_discount_service, promo_discount_delivery, promo_discount_vendor,
    wallet_used, total, payment_method, deposit_required, deposit_amount,
    idempotency_key
  ) values (
    p_order_id, v_version, 'offered', auth.uid(), v_expires_at,
    v_snapshot.subtotal, v_snapshot.delivery_fee, v_snapshot.service_fee, v_snapshot.promo_code_id,
    v_snapshot.promo_discount, v_snapshot.promo_discount_service,
    v_snapshot.promo_discount_delivery, v_snapshot.promo_discount_vendor,
    v_snapshot.wallet_used, v_snapshot.total, v_snapshot.payment_method,
    v_snapshot.deposit_required, v_snapshot.deposit_amount,
    p_idempotency_key
  ) returning id into v_quote_id;

  update orders
     set quote_state = 'offered', current_quote_id = v_quote_id
   where id = p_order_id;

  perform private.notify_quote_customer(
    p_order_id, v_quote_id, 'quote_offered', 'سالكة — سعر طلبك جاهز',
    'راجع السعر ووافق خلال 15 دقيقة عشان نبدأ طلبك'
  );

  insert into order_status_events (order_id, from_status, to_status, actor, actor_uid)
  values (p_order_id, 'quote:' || coalesce(v_order.quote_state, 'pending'), 'quote:offered',
          case when is_admin() then 'admin' else 'supervisor' end, auth.uid());
  perform private.record_order_event(
    p_order_id, 'quote.offered', 'quote', jsonb_build_object('state', coalesce(v_order.quote_state, 'pending')),
    jsonb_build_object('state', 'offered', 'quote_id', v_quote_id, 'version', v_version, 'expires_at', v_expires_at),
    case when is_admin() then 'admin' else 'supervisor' end, null, p_idempotency_key
  );

  return json_build_object('quote_id', v_quote_id, 'version', v_version, 'state', 'offered');
end;
$function$;

create or replace function public.issue_custom_order_quote(
  p_order_id integer,
  p_subtotal numeric,
  p_expires_at timestamptz,
  p_idempotency_key uuid,
  p_auth_user_id uuid default null
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if p_auth_user_id is null then raise exception 'not_authorized'; end if;
  perform set_config('request.jwt.claim.sub', p_auth_user_id::text, true);
  return private.issue_custom_order_quote(p_order_id, p_subtotal, p_expires_at, p_idempotency_key);
end;
$function$;

revoke all on function private.issue_custom_order_quote(integer,numeric,timestamptz,uuid) from public, anon, authenticated;
revoke all on function public.issue_custom_order_quote(integer,numeric,timestamptz,uuid,uuid) from public, anon, authenticated;
grant execute on function public.issue_custom_order_quote(integer,numeric,timestamptz,uuid,uuid) to service_role;

create or replace function private.accept_custom_order_quote(
  p_order_id integer,
  p_quote_id bigint,
  p_order_token uuid,
  p_idempotency_key uuid
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_order orders%rowtype;
  v_quote order_quotes%rowtype;
  v_wallet_refund numeric;
  v_payment_due boolean;
  v_next_status text;
begin
  select * into v_order from orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_order.public_token <> p_order_token then raise exception 'invalid_quote_token'; end if;
  if v_order.status = 'Cancelled' then raise exception 'order_closed'; end if;

  select * into v_quote from order_quotes where id = p_quote_id and order_id = p_order_id for update;
  if not found then raise exception 'quote_not_found'; end if;
  if v_order.current_quote_id is distinct from v_quote.id then raise exception 'quote_not_current'; end if;
  if v_quote.state = 'accepted' then
    return json_build_object('quote_id', v_quote.id, 'state', 'accepted', 'order_status', v_order.status);
  end if;
  if v_quote.state <> 'offered' then raise exception 'quote_not_offered'; end if;
  if v_quote.expires_at <= now() then
    update order_quotes set state = 'expired' where id = v_quote.id;
    update orders set quote_state = 'expired' where id = p_order_id;
    insert into order_status_events (order_id, from_status, to_status, actor)
      values (p_order_id, 'quote:offered', 'quote:expired', 'system');
    perform private.record_order_event(
      p_order_id, 'quote.expired', 'quote',
      jsonb_build_object('state', 'offered', 'quote_id', v_quote.id),
      jsonb_build_object('state', 'expired', 'quote_id', v_quote.id),
      'system', null, p_idempotency_key
    );
    perform private.notify_quote_customer(
      p_order_id, v_quote.id, 'quote_expired', 'سالكة — انتهت صلاحية عرض السعر',
      'العرض انتهى. هنراجع طلبك ونبعتلك عرض جديد لو لسه محتاجه'
    );
    -- Do not raise here: an uncaught exception would roll back the state/event
    -- and transactional push request above. The caller reloads and renders the
    -- persisted terminal quote state instead.
    return json_build_object('quote_id', v_quote.id, 'state', 'expired');
  end if;

  -- The quote snapshot is now authoritative. No live pricing helper is called
  -- here, so later settings or promotion changes cannot rewrite customer terms.
  v_wallet_refund := greatest(0, coalesce(v_order.wallet_used, 0) - v_quote.wallet_used);
  if v_wallet_refund > 0 then
    update customer_wallets
       set balance = balance + v_wallet_refund
     where phone = normalize_phone(v_order.customer_phone);
    insert into wallet_transactions (wallet_id, amount, reason, order_id)
      select id, v_wallet_refund, 'استرجاع رصيد بعد قبول عرض سعر', p_order_id
        from customer_wallets where phone = normalize_phone(v_order.customer_phone);
  end if;

  v_payment_due := (v_quote.deposit_required or (v_quote.payment_method in ('online', 'instapay') and v_quote.total > 0));
  v_next_status := case
    when v_payment_due then 'awaiting_payment'
    when v_order.slot_id is not null and coalesce(v_order.dispatch_at, v_order.created_at) > now() then 'Scheduled'
    else 'pending'
  end;

  update order_quotes
     set state = 'accepted', accepted_at = now(), accepted_by = auth.uid()
   where id = v_quote.id;

  update orders
     set quote_state = 'accepted',
         subtotal = v_quote.subtotal,
         delivery_fee = v_quote.delivery_fee,
         service_fee = v_quote.service_fee,
         promo_code_id = v_quote.promo_code_id,
         promo_discount = v_quote.promo_discount,
         promo_discount_service = v_quote.promo_discount_service,
         promo_discount_delivery = v_quote.promo_discount_delivery,
         promo_discount_vendor = v_quote.promo_discount_vendor,
         wallet_used = v_quote.wallet_used,
         total = v_quote.total,
         pricing_status = 'confirmed',
         cod_deposit_amount = case when v_quote.deposit_required then v_quote.deposit_amount else null end,
         online_payment_status = case when v_payment_due then 'pending' else null end,
         status = v_next_status
   where id = p_order_id;

  insert into order_status_events (order_id, from_status, to_status, actor, actor_uid)
    values (p_order_id, 'quote:offered', 'quote:accepted', 'customer', auth.uid());
  perform private.record_order_event(
    p_order_id, 'quote.accepted', 'quote', jsonb_build_object('state', 'offered', 'quote_id', v_quote.id),
    jsonb_build_object('state', 'accepted', 'quote_id', v_quote.id), 'customer', null, p_idempotency_key
  );
  perform private.record_order_event(
    p_order_id, 'payment.required', 'payment', null,
    jsonb_build_object('deposit_required', v_quote.deposit_required, 'deposit_amount', v_quote.deposit_amount,
      'payment_pending', v_payment_due), 'system', null, p_idempotency_key
  );

  return json_build_object('quote_id', v_quote.id, 'state', 'accepted', 'order_status', v_next_status);
end;
$function$;

create or replace function private.reject_custom_order_quote(
  p_order_id integer,
  p_quote_id bigint,
  p_order_token uuid,
  p_reason text default '',
  p_idempotency_key uuid default null
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_order orders%rowtype;
  v_quote order_quotes%rowtype;
begin
  if length(coalesce(p_reason, '')) > 500 then raise exception 'reason_too_long'; end if;
  select * into v_order from orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  if v_order.public_token <> p_order_token then raise exception 'invalid_quote_token'; end if;
  if v_order.status = 'Cancelled' then raise exception 'order_closed'; end if;

  select * into v_quote from order_quotes where id = p_quote_id and order_id = p_order_id for update;
  if not found then raise exception 'quote_not_found'; end if;
  if v_order.current_quote_id is distinct from v_quote.id then raise exception 'quote_not_current'; end if;
  if v_quote.state = 'rejected' then return json_build_object('quote_id', v_quote.id, 'state', 'rejected'); end if;
  if v_quote.state <> 'offered' then raise exception 'quote_not_offered'; end if;
  if v_quote.expires_at <= now() then
    update order_quotes set state = 'expired' where id = v_quote.id;
    update orders set quote_state = 'expired' where id = p_order_id;
    insert into order_status_events (order_id, from_status, to_status, actor)
      values (p_order_id, 'quote:offered', 'quote:expired', 'system');
    perform private.record_order_event(
      p_order_id, 'quote.expired', 'quote',
      jsonb_build_object('state', 'offered', 'quote_id', v_quote.id),
      jsonb_build_object('state', 'expired', 'quote_id', v_quote.id),
      'system', null, p_idempotency_key
    );
    perform private.notify_quote_customer(
      p_order_id, v_quote.id, 'quote_expired', 'سالكة — انتهت صلاحية عرض السعر',
      'العرض انتهى. هنراجع طلبك ونبعتلك عرض جديد لو لسه محتاجه'
    );
    return json_build_object('quote_id', v_quote.id, 'state', 'expired');
  end if;

  update order_quotes
     set state = 'rejected', rejected_at = now(), rejected_by = auth.uid(),
         rejection_reason = nullif(trim(coalesce(p_reason, '')), '')
   where id = v_quote.id;
  update orders set quote_state = 'rejected' where id = p_order_id;

  insert into order_status_events (order_id, from_status, to_status, actor, actor_uid)
    values (p_order_id, 'quote:offered', 'quote:rejected', 'customer', auth.uid());
  perform private.record_order_event(
    p_order_id, 'quote.rejected', 'quote', jsonb_build_object('state', 'offered', 'quote_id', v_quote.id),
    jsonb_build_object('state', 'rejected', 'quote_id', v_quote.id), 'customer', p_reason, p_idempotency_key
  );
  return json_build_object('quote_id', v_quote.id, 'state', 'rejected');
end;
$function$;

create or replace function public.accept_custom_order_quote(
  p_order_id integer, p_quote_id bigint, p_order_token uuid,
  p_idempotency_key uuid, p_auth_user_id uuid default null
)
returns json language plpgsql security definer set search_path to 'public' as $function$
begin
  if p_idempotency_key is null then raise exception 'invalid_idempotency_key'; end if;
  if p_auth_user_id is not null then perform set_config('request.jwt.claim.sub', p_auth_user_id::text, true); end if;
  return private.accept_custom_order_quote(p_order_id, p_quote_id, p_order_token, p_idempotency_key);
end;
$function$;

create or replace function public.reject_custom_order_quote(
  p_order_id integer, p_quote_id bigint, p_order_token uuid, p_reason text default '',
  p_idempotency_key uuid default null, p_auth_user_id uuid default null
)
returns json language plpgsql security definer set search_path to 'public' as $function$
begin
  if p_idempotency_key is null then raise exception 'invalid_idempotency_key'; end if;
  if p_auth_user_id is not null then perform set_config('request.jwt.claim.sub', p_auth_user_id::text, true); end if;
  return private.reject_custom_order_quote(p_order_id, p_quote_id, p_order_token, p_reason, p_idempotency_key);
end;
$function$;

revoke all on function private.accept_custom_order_quote(integer,bigint,uuid,uuid), private.reject_custom_order_quote(integer,bigint,uuid,text,uuid) from public, anon, authenticated;
revoke all on function public.accept_custom_order_quote(integer,bigint,uuid,uuid,uuid), public.reject_custom_order_quote(integer,bigint,uuid,text,uuid,uuid) from public, anon, authenticated;
grant execute on function public.accept_custom_order_quote(integer,bigint,uuid,uuid,uuid), public.reject_custom_order_quote(integer,bigint,uuid,text,uuid,uuid) to service_role;

create or replace function private.get_current_custom_order_quote(
  p_order_id integer,
  p_order_token uuid
)
returns json
language sql
security definer
set search_path to 'public'
as $function$
  select case
    when o.public_token <> p_order_token then null
    else (
      select json_build_object(
        'id', q.id, 'version', q.version, 'state', q.state, 'expires_at', q.expires_at,
        'subtotal', q.subtotal, 'delivery_fee', q.delivery_fee, 'service_fee', q.service_fee,
        'promo_discount', q.promo_discount, 'wallet_used', q.wallet_used, 'total', q.total,
        'deposit_required', q.deposit_required, 'deposit_amount', q.deposit_amount
      )
      from order_quotes q where q.id = o.current_quote_id
    )
  end
  from orders o where o.id = p_order_id;
$function$;

create or replace function public.get_current_custom_order_quote(
  p_order_id integer, p_order_token uuid, p_auth_user_id uuid default null
)
returns json language plpgsql security definer set search_path to 'public' as $function$
begin
  if p_auth_user_id is not null then perform set_config('request.jwt.claim.sub', p_auth_user_id::text, true); end if;
  return private.get_current_custom_order_quote(p_order_id, p_order_token);
end;
$function$;

revoke all on function private.get_current_custom_order_quote(integer,uuid) from public, anon, authenticated;
revoke all on function public.get_current_custom_order_quote(integer,uuid,uuid) from public, anon, authenticated;
grant execute on function public.get_current_custom_order_quote(integer,uuid,uuid) to service_role;

-- The function is callable for deterministic tests and is also scheduled below
-- in this local migration draft. Production scheduling remains untouched until
-- this migration is explicitly reviewed and applied.
create or replace function private.expire_custom_order_quotes()
returns integer
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_expired_ids bigint[];
  v_count integer;
  v_quote record;
begin
  -- One reminder per quote, inside the final two minutes. The caller must run
  -- this sweep at least once per minute for the reminder window to be useful.
  for v_quote in
    update order_quotes
       set reminder_sent_at = now()
     where state = 'offered'
       and reminder_sent_at is null
       and expires_at > now()
       and expires_at <= now() + interval '2 minutes'
     returning id, order_id
  loop
    perform private.notify_quote_customer(
      v_quote.order_id, v_quote.id, 'quote_expiring', 'سالكة — العرض هينتهي قريب',
      'قدامك أقل من دقيقتين توافق على سعر طلبك'
    );
  end loop;

  with expired as (
    update order_quotes q
       set state = 'expired'
     where q.state = 'offered' and q.expires_at <= now()
     returning q.id, q.order_id
  )
  select array_agg(id), count(*) into v_expired_ids, v_count from expired;

  if coalesce(v_count, 0) = 0 then return 0; end if;

  update orders o
     set quote_state = 'expired'
   where o.current_quote_id = any(v_expired_ids)
     and o.quote_state = 'offered';

  insert into order_status_events (order_id, from_status, to_status, actor)
  select q.order_id, 'quote:offered', 'quote:expired', 'system'
    from order_quotes q where q.id = any(v_expired_ids);

  insert into order_events (order_id, event_type, state_dimension, before_state, after_state, actor_role)
  select q.order_id, 'quote.expired', 'quote',
         jsonb_build_object('state', 'offered', 'quote_id', q.id),
         jsonb_build_object('state', 'expired', 'quote_id', q.id), 'system'
    from order_quotes q where q.id = any(v_expired_ids);

  for v_quote in
    select id, order_id from order_quotes where id = any(v_expired_ids)
  loop
    perform private.notify_quote_customer(
      v_quote.order_id, v_quote.id, 'quote_expired', 'سالكة — انتهت صلاحية عرض السعر',
      'العرض انتهى. هنراجع طلبك ونبعتلك عرض جديد لو لسه محتاجه'
    );
  end loop;

  return v_count;
end;
$function$;

create or replace function public.expire_custom_order_quotes(p_auth_user_id uuid default null)
returns integer language plpgsql security definer set search_path to 'public' as $function$
begin
  if p_auth_user_id is not null then perform set_config('request.jwt.claim.sub', p_auth_user_id::text, true); end if;
  return private.expire_custom_order_quotes();
end;
$function$;

revoke all on function private.expire_custom_order_quotes() from public, anon, authenticated;
revoke all on function public.expire_custom_order_quotes(uuid) from public, anon, authenticated;
grant execute on function public.expire_custom_order_quotes(uuid) to service_role;

-- Runs independently of the customer app. It handles both the <2-minute push
-- reminder and the terminal expiry push, even while a device is locked.
select cron.schedule(
  'quote-expiry-sweep',
  '* * * * *',
  $$select public.expire_custom_order_quotes()$$
);

-- The legacy status trigger predates quote_state and treats every
-- pending_quote -> confirmed update as “price ready”. In the new flow that
-- update happens only after the customer has already seen and accepted the
-- offer, so suppress that stale duplicate while preserving all other order
-- lifecycle notifications.
create or replace function public.notify_order_status_change()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare v_secret text; v_title text; v_body text;
begin
  if new.push_token is null then return new; end if;
  if new.status = 'Accepted' and old.status is distinct from 'Accepted' then
    v_title := 'سالكة'; v_body := 'مندوبك في الطريق لاستلام طلبك';
  elsif new.status = 'Cancelled' and old.status is distinct from 'Cancelled' then
    v_title := 'سالكة'; v_body := 'للأسف اتلغى طلبك' ||
      case when new.cancel_reason is not null and new.cancel_reason <> '' then ' -- ' || new.cancel_reason else '' end;
  elsif new.status = 'Out_for_Delivery' and old.status is distinct from 'Out_for_Delivery' then
    v_title := 'سالكة'; v_body := 'مندوبك في الطريق إليك 🛵';
  elsif new.status = 'Delivered' and old.status is distinct from 'Delivered' then
    v_title := 'سالكة'; v_body := 'تم توصيل طلبك، بالهنا والشفا 🎉';
  elsif new.pricing_status = 'confirmed'
    and old.pricing_status is distinct from 'confirmed'
    and coalesce(new.quote_state, '') <> 'accepted' then
    v_title := 'سالكة'; v_body := 'سعر طلبك جاهز -- ادفع علشان نبدأ فيه';
  elsif new.kitchen_status = 'preparing' and old.kitchen_status is distinct from 'preparing' then
    v_title := 'سالكة'; v_body := 'المطعم بدأ يجهز طلبك';
  elsif new.kitchen_status = 'ready' and old.kitchen_status is distinct from 'ready' then
    v_title := 'سالكة'; v_body := 'طلبك جاهز وهيتسلم للمندوب دلوقتي';
  else
    return new;
  end if;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'push_webhook_secret';
  perform net.http_post(
    url := 'https://pqpnwxyevrsipklzmwex.supabase.co/functions/v1/send-push',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-webhook-secret', coalesce(v_secret,'')),
    body := jsonb_build_object(
      'tokens', jsonb_build_array(jsonb_build_object('token', new.push_token, 'platform', coalesce(new.push_platform, 'web'))),
      'title', v_title, 'body', v_body,
      'data', jsonb_build_object('order_id', new.id, 'link', '/track/' || new.public_token)
    )
  );
  return new;
exception when others then
  return new;
end;
$function$;

-- A UI filter is helpful, but dispatch can also be initiated by an RPC,
-- dashboard, or future integration. Keep the canonical quote transition as a
-- database invariant at the point an assignment is created or moved.
create or replace function private.guard_custom_order_quote_dispatch()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_order_type text;
  v_quote_state text;
begin
  select order_type, quote_state
    into v_order_type, v_quote_state
    from public.orders
   where id = new.order_id;

  if v_order_type = 'custom_request'
     and v_quote_state is not null
     and v_quote_state <> 'accepted' then
    raise exception 'quote_not_accepted';
  end if;

  return new;
end;
$function$;

drop trigger if exists guard_custom_order_quote_dispatch on public.delivery_assignments;
create trigger guard_custom_order_quote_dispatch
before insert or update of order_id on public.delivery_assignments
for each row execute function private.guard_custom_order_quote_dispatch();

-- The vendor-operation RPCs are security definer functions, so RLS alone does
-- not protect a custom request if a future operation changes kitchen_status.
-- Reject that progression at the row itself until the quote is accepted and a
-- required payment is no longer pending.
create or replace function private.guard_custom_order_quote_fulfilment()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  if new.status <> 'Cancelled'
     and new.order_type = 'custom_request'
     and new.quote_state is not null
     and new.quote_state <> 'accepted' then
    raise exception 'quote_not_accepted';
  end if;
  if new.order_type = 'custom_request' and new.status = 'awaiting_payment' then
    raise exception 'order_not_paid';
  end if;
  return new;
end;
$function$;

drop trigger if exists guard_custom_order_quote_fulfilment on public.orders;
create trigger guard_custom_order_quote_fulfilment
before update of kitchen_status on public.orders
for each row
when (new.kitchen_status is distinct from old.kitchen_status)
execute function private.guard_custom_order_quote_fulfilment();

do $verification$
declare v_signature text;
begin
  if not (select relrowsecurity from pg_class where oid = 'public.order_quotes'::regclass)
     or not (select relrowsecurity from pg_class where oid = 'public.order_events'::regclass) then
    raise exception 'quote_audit_rls_required';
  end if;
  if not exists (
    select 1 from pg_constraint
     where conrelid = 'public.orders'::regclass
       and conname = 'orders_current_quote_matches_order_fk'
  ) then
    raise exception 'current_quote_order_integrity_missing';
  end if;
  if has_function_privilege('service_role', 'public.confirm_custom_order_price(integer,numeric,uuid)', 'execute') then
    raise exception 'legacy_quote_confirmation_still_callable';
  end if;
  if not exists (
    select 1 from pg_trigger
     where tgrelid = 'public.delivery_assignments'::regclass
       and tgname = 'guard_custom_order_quote_dispatch'
       and not tgisinternal
  ) then
    raise exception 'quote_dispatch_guard_missing';
  end if;
  if not exists (
    select 1 from pg_trigger
     where tgrelid = 'public.orders'::regclass
       and tgname = 'initialize_order_quote_state'
       and not tgisinternal
  ) then
    raise exception 'quote_state_initializer_missing';
  end if;
  if not exists (
    select 1 from pg_trigger
     where tgrelid = 'public.orders'::regclass
       and tgname = 'guard_custom_order_quote_fulfilment'
       and not tgisinternal
  ) then
    raise exception 'quote_fulfilment_guard_missing';
  end if;

  foreach v_signature in array array[
    'public.issue_custom_order_quote(integer,numeric,timestamp with time zone,uuid,uuid)',
    'public.accept_custom_order_quote(integer,bigint,uuid,uuid,uuid)',
    'public.reject_custom_order_quote(integer,bigint,uuid,text,uuid,uuid)',
    'public.get_current_custom_order_quote(integer,uuid,uuid)',
    'public.expire_custom_order_quotes(uuid)'
  ] loop
    if has_function_privilege('anon', v_signature, 'execute')
       or has_function_privilege('authenticated', v_signature, 'execute')
       or not has_function_privilege('service_role', v_signature, 'execute') then
      raise exception 'invalid quote rpc privilege for %', v_signature;
    end if;
  end loop;
end;
$verification$;

comment on table public.order_quotes is
  'Immutable custom-order quote snapshots. A customer must accept a current version before fulfilment can proceed.';
comment on column public.orders.quote_state is
  'Canonical quote dimension. NULL is intentionally retained for historical staff-confirmed custom orders until explicitly resolved.';
