-- Observer accounts and server-authoritative optional promotional codes.
-- This migration intentionally leaves existing automatic menu discounts unchanged.

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  active boolean not null default true,
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  max_discount_egp numeric(12,2),
  minimum_subtotal_egp numeric(12,2) not null default 0 check (minimum_subtotal_egp >= 0),
  restaurant_id integer references public.restaurants(id) on delete cascade,
  compound_id integer references public.compounds(id) on delete cascade,
  starts_at timestamptz,
  ends_at timestamptz,
  max_redemptions integer,
  max_redemptions_per_customer integer not null default 1 check (max_redemptions_per_customer > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  constraint promo_codes_code_format check (code = upper(trim(code)) and code ~ '^[A-Z0-9][A-Z0-9_-]{2,31}$'),
  constraint promo_codes_percent_range check (discount_type <> 'percent' or discount_value <= 100),
  constraint promo_codes_max_discount check (max_discount_egp is null or max_discount_egp > 0),
  constraint promo_codes_dates check (ends_at is null or starts_at is null or ends_at > starts_at),
  constraint promo_codes_max_redemptions check (max_redemptions is null or max_redemptions > 0)
);
create unique index if not exists promo_codes_code_key on public.promo_codes (code);

alter table public.orders
  add column if not exists promo_code_id bigint references public.promo_codes(id) on delete set null,
  add column if not exists promo_discount numeric(12,2) not null default 0 check (promo_discount >= 0);

create table if not exists public.promo_redemptions (
  id bigint generated by default as identity primary key,
  promo_code_id bigint not null references public.promo_codes(id) on delete restrict,
  order_id integer not null references public.orders(id) on delete restrict,
  customer_key text not null,
  discount_amount numeric(12,2) not null check (discount_amount > 0),
  redeemed_at timestamptz not null default now(),
  unique (order_id)
);
create index if not exists promo_redemptions_customer_idx on public.promo_redemptions (promo_code_id, customer_key);

alter table public.promo_codes enable row level security;
alter table public.promo_redemptions enable row level security;
revoke all on public.promo_codes, public.promo_redemptions from anon, authenticated;

create or replace function private.apply_order_promo(
  p_order_id integer, p_code text, p_customer_id integer default null, p_customer_phone text default null
) returns numeric
language plpgsql security definer set search_path = public
as $$
declare
  v_order orders%rowtype; v_promo promo_codes%rowtype; v_code text;
  v_key text; v_used integer; v_discount numeric; v_gross numeric; v_final_gross numeric;
  v_new_wallet numeric; v_wallet_refund numeric := 0; v_threshold numeric; v_deposit numeric;
begin
  v_code := upper(trim(coalesce(p_code,'')));
  if v_code = '' then return 0; end if;
  if v_code !~ '^[A-Z0-9][A-Z0-9_-]{2,31}$' then raise exception 'invalid_promo_code'; end if;
  select * into v_order from orders where id = p_order_id for update;
  if not found then raise exception 'order_not_found'; end if;
  select * into v_promo from promo_codes where code = v_code for update;
  if not found or not v_promo.active then raise exception 'promo_invalid'; end if;
  if (v_promo.starts_at is not null and now() < v_promo.starts_at)
     or (v_promo.ends_at is not null and now() >= v_promo.ends_at) then raise exception 'promo_expired'; end if;
  if v_promo.restaurant_id is not null and v_promo.restaurant_id <> v_order.restaurant_id then raise exception 'promo_not_available'; end if;
  if v_promo.compound_id is not null and v_promo.compound_id <> v_order.compound_id then raise exception 'promo_not_available'; end if;
  if v_order.subtotal < v_promo.minimum_subtotal_egp then raise exception 'promo_minimum_not_met'; end if;
  if v_promo.max_redemptions is not null and (select count(*) from promo_redemptions where promo_code_id = v_promo.id) >= v_promo.max_redemptions then
    raise exception 'promo_limit_reached';
  end if;
  v_key := case when p_customer_id is not null then 'customer:' || p_customer_id::text else 'phone:' || normalize_phone(p_customer_phone) end;
  if v_key is null or right(v_key,1) = ':' then raise exception 'promo_customer_missing'; end if;
  select count(*) into v_used from promo_redemptions where promo_code_id = v_promo.id and customer_key = v_key;
  if v_used >= v_promo.max_redemptions_per_customer then raise exception 'promo_already_used'; end if;

  v_discount := case when v_promo.discount_type = 'percent'
    then round(v_order.subtotal * v_promo.discount_value / 100.0, 2)
    else least(v_order.subtotal, v_promo.discount_value) end;
  if v_promo.max_discount_egp is not null then v_discount := least(v_discount, v_promo.max_discount_egp); end if;
  if v_discount <= 0 then raise exception 'promo_invalid'; end if;
  v_gross := v_order.subtotal + v_order.delivery_fee + coalesce(v_order.service_fee,0);
  v_final_gross := greatest(0, v_gross - v_discount);
  v_new_wallet := least(coalesce(v_order.wallet_used,0), v_final_gross);
  v_wallet_refund := coalesce(v_order.wallet_used,0) - v_new_wallet;
  if v_wallet_refund > 0 then
    update customer_wallets set balance = balance + v_wallet_refund
      where phone = normalize_phone(v_order.customer_phone);
    insert into wallet_transactions(wallet_id, amount, reason, order_id)
      select id, v_wallet_refund, 'استرجاع رصيد بعد كود خصم', p_order_id
      from customer_wallets where phone = normalize_phone(v_order.customer_phone);
  end if;
  select coalesce((select value::numeric from settings where key = 'cod_deposit_threshold_egp'),3000) into v_threshold;
  v_deposit := case when v_order.payment_method = 'cod' and v_final_gross - v_new_wallet > v_threshold
    then ceil((v_final_gross - v_new_wallet) * .5) else null end;
  update orders set promo_code_id=v_promo.id, promo_discount=v_discount, wallet_used=v_new_wallet,
    total=v_final_gross-v_new_wallet, cod_deposit_amount=v_deposit,
    online_payment_status=case when (payment_method in ('online','instapay') and v_final_gross-v_new_wallet > 0) or v_deposit is not null then 'pending' else null end,
    status=case when status='awaiting_payment' and v_final_gross-v_new_wallet=0 then 'pending' else status end
  where id=p_order_id;
  insert into promo_redemptions(promo_code_id,order_id,customer_key,discount_amount)
    values(v_promo.id,p_order_id,v_key,v_discount);
  return v_discount;
end $$;

revoke all on function private.apply_order_promo(integer,text,integer,text) from public;

-- Use the existing hardened 17-argument entry point, then apply the optional
-- code within its transaction. The Edge Function always sends p_promo_code.
create or replace function public.place_order(
  p_restaurant_id integer,p_customer_name text,p_customer_phone text,p_zone text,p_unit_number text,p_address_notes text,
  p_delivery_fee numeric,p_items json,p_slot_id integer default null,p_scheduled_date date default null,
  p_compound_id integer default null,p_payment_method text default 'cod',p_use_wallet boolean default false,
  p_session_token uuid default null,p_customer_note text default null,p_rate_key text default null,p_auth_user_id uuid default null,
  p_promo_code text default null
) returns json language plpgsql security definer set search_path = public as $$
declare v_result json; v_order_id integer; v_customer_id integer; v_discount numeric;
begin
  v_result := public.place_order(p_restaurant_id,p_customer_name,p_customer_phone,p_zone,p_unit_number,p_address_notes,
    p_delivery_fee,p_items,p_slot_id,p_scheduled_date,p_compound_id,p_payment_method,p_use_wallet,p_session_token,p_customer_note,p_rate_key,p_auth_user_id);
  if nullif(trim(coalesce(p_promo_code,'')),'') is not null then
    select customer_id into v_customer_id from orders where id=(v_result->>'id')::integer;
    v_discount := private.apply_order_promo((v_result->>'id')::integer,p_promo_code,v_customer_id,p_customer_phone);
    v_result := v_result || json_build_object('promo_discount',v_discount);
  end if;
  return v_result;
end $$;
grant execute on function public.place_order(integer,text,text,text,text,text,numeric,json,integer,date,integer,text,boolean,uuid,text,text,uuid,text) to anon, authenticated;

create or replace function private.quote_promo_code(p_code text,p_restaurant_id integer,p_compound_id integer,p_subtotal numeric)
returns json language plpgsql security definer set search_path = public as $$
declare p promo_codes%rowtype; d numeric;
begin
 select * into p from promo_codes where code=upper(trim(coalesce(p_code,'')));
 if not found or not p.active then return json_build_object('valid',false,'reason','promo_invalid'); end if;
 if (p.starts_at is not null and now()<p.starts_at) or (p.ends_at is not null and now()>=p.ends_at) then return json_build_object('valid',false,'reason','promo_expired'); end if;
 if (p.restaurant_id is not null and p.restaurant_id<>p_restaurant_id) or (p.compound_id is not null and p.compound_id<>p_compound_id) then return json_build_object('valid',false,'reason','promo_not_available'); end if;
 if p_subtotal<p.minimum_subtotal_egp then return json_build_object('valid',false,'reason','promo_minimum_not_met','minimum',p.minimum_subtotal_egp); end if;
 d:=case when p.discount_type='percent' then round(p_subtotal*p.discount_value/100,2) else least(p_subtotal,p.discount_value) end;
 if p.max_discount_egp is not null then d:=least(d,p.max_discount_egp); end if;
 return json_build_object('valid',true,'discount',d,'code',p.code);
end $$;
create or replace function public.quote_promo_code(p_code text,p_restaurant_id integer,p_compound_id integer,p_subtotal numeric)
returns json language sql security definer set search_path = public as $$
 select private.quote_promo_code(p_code,p_restaurant_id,p_compound_id,p_subtotal)
$$;
grant execute on function public.quote_promo_code(text,integer,integer,numeric) to anon, authenticated;

-- Observer is a role, but never inherits supervisor/admin permissions.
-- Account creation is handled by the existing admin-accounts function update.
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('admin','driver','vendor','catalog','supervisor','observer'));

create or replace function private.observer_dashboard()
returns json language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from profiles where id = auth.uid() and role in ('observer','admin')) then
    raise exception 'observer_only';
  end if;
  return json_build_object(
    'today', (select count(*) from orders where created_at >= date_trunc('day', now() at time zone 'Africa/Cairo') at time zone 'Africa/Cairo' and not coalesce(is_test,false)),
    'yesterday', (select count(*) from orders where created_at >= (date_trunc('day', now() at time zone 'Africa/Cairo') - interval '1 day') at time zone 'Africa/Cairo' and created_at < date_trunc('day', now() at time zone 'Africa/Cairo') at time zone 'Africa/Cairo' and not coalesce(is_test,false)),
    'incoming', (select count(*) from orders where status in ('pending','Scheduled','awaiting_payment') and not coalesce(is_test,false)),
    'ready', (select count(*) from orders where status='Accepted' and kitchen_status='ready' and not coalesce(is_test,false)),
    'on_way', (select count(*) from orders where status in ('Picked_Up','Out_for_Delivery') and not coalesce(is_test,false)),
    'delivered_today', (select count(*) from delivery_assignments a join orders o on o.id=a.order_id where a.status='Delivered' and a.delivered_at >= date_trunc('day', now() at time zone 'Africa/Cairo') at time zone 'Africa/Cairo' and not coalesce(o.is_test,false)),
    'recent', coalesce((select json_agg(x) from (
      select o.id, r.name as restaurant_name, o.status, o.kitchen_status, o.created_at
      from orders o join restaurants r on r.id=o.restaurant_id
      where not coalesce(o.is_test,false) order by o.created_at desc limit 20
    ) x), '[]'::json)
  );
end $$;
revoke all on function private.observer_dashboard() from public;
create or replace function public.observer_dashboard()
returns json language sql security definer set search_path = public as $$ select private.observer_dashboard() $$;
revoke all on function public.observer_dashboard() from public;
grant execute on function public.observer_dashboard() to authenticated;
